MakerShop/MakerShop/Controllers/MyProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MakerShop.Models;
using System.IO;

namespace MakerShop.Controllers
{
    public class MyProductsController : Controller
    {
        private MakerShopDataEntities db = new MakerShopDataEntities();


        //GET: Items/AddImage
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult AddImage()
        {
            ViewBag.Complete = 0;

            return View();
        }


        [HttpPost]
        public ActionResult AddImage(HttpPostedFileBase file)
        {
            ViewBag.Complete = 0;
            if (ModelState.IsValid)
            {
                if (file == null)
                {
                    ModelState.AddModelError("File", "Please Upload Your file");
                }
                else if (file.ContentLength > 0)
                {
                    int MaxContentLength = 1024 * 1024 * 3; //3 MB
                    string[] AllowedFileExtensions = new string[] { ".jpg" };

                    if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                    {
                        ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                    }

                    else if (file.ContentLength > MaxContentLength)
                    {
                        ModelState.AddModelError("File", "Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                    }
                    else
                    {
                        //TO:DO
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content"), fileName);
                        file.SaveAs(path);
                        ModelState.Clear();
                        //int itemNum = (int)Session["ItemEdited"];
                        //  db.addImage(fileName, itemNum);
                        //  Session["ItemEdited"] = 0;
                        ViewBag.Message = "File uploaded successfully";
                        ViewBag.Complete = 1;
                    }
                }
            }
            return View();
        }




        // GET: MyProducts
        public ActionResult Index()
        {
            var models = db.Models.Include(m => m.User);
            return View(models.ToList());
        }

        // GET: MyProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // GET: MyProducts/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName");
            return View();
        }

        // POST: MyProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ModelID,ModelName,Size,UserID,Download")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Models.Add(model);
                db.SaveChanges();
                return RedirectToAction("AddImage");
            }

            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", model.UserID);
            return View(model);
        }

        // GET: MyProducts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", model.UserID);
            return View(model);
        }

        // POST: MyProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ModelID,ModelName,Size,UserID,Download")] Model model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "UserName", model.UserID);
            return View(model);
        }

        // GET: MyProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Model model = db.Models.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: MyProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Model model = db.Models.Find(id);
            db.Models.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MakerShop/MakerShop/Views/MyProducts/AddImage.cshtml
@{
    ViewBag.Title = "AddImage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add Image</h2>

@ViewBag.Message
@{int complete = (int)ViewBag.Complete;}

@if (complete != 1)
{
    using (Html.BeginForm("AddImage", "MyProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary();
    <ol>
        <li class="lifile">
            <input type="file" id="fileToUpload" name="file" />
            <span class="field-validation-error" id="spanfile"></span>
        </li>
    </ol>
    <input type="submit" id="btnSubmit" value="Add Image" />
    }

    <script type="text/jscript">
        //get file size
        function GetFileSize(fileid) {
            try {
                var fileSize = 0;
                //for IE
                if ($.browser.msie) {
                    //before making an object of ActiveXObject,
                    //please make sure ActiveX is enabled in your IE browser
                    var objFSO = new ActiveXObject("Scripting.FileSystemObject"); var filePath = $("#" + fileid)[0].value;
                    var objFile = objFSO.getFile(filePath);
                    var fileSize = objFile.size; //size in kb
                    fileSize = fileSize / 1048576; //size in mb
                }
                    //for FF, Safari, Opeara and Others
                else {
                    fileSize = $("#" + fileid)[0].files[0].size //size in kb
                    fileSize = fileSize / 1048576; //size in mb
                }
                return fileSize;
            }
            catch (e) {
                alert("Error is :" + e);
            }
        }

        //get file path from client system
        function getNameFromPath(strFilepath) {
            var objRE = new RegExp(/([^\/\\]+)$/);
            var strName = objRE.exec(strFilepath);

            if (strName == null) {
                return null;
            }
            else {
                return strName[0];
            }
        }

        $("#btnSubmit").live("click", function () {
            if ($('#fileToUpload').val() == "") {
                $("#spanfile").html("Please upload file");
                return false;
            }
            else {
                return checkfile();
            }
        });

        function checkfile() {
            var file = getNameFromPath($("#fileToUpload").val());
            if (file != null) {
                var extension = file.substr((file.lastIndexOf('.') + 1));
                // alert(extension);
                switch (extension) {
                    case 'jpg':
                    case 'png':
                    case 'gif':
                    case 'pdf':
                        flag = true;
                        break;
                    default:
                        flag = false;
                }
            }
            if (flag == false) {
                $("#spanfile").text("You can upload only jpg,png,gif,pdf extension file");
                return false;
            }
            else {
                var size = GetFileSize('fileToUpload');
                if (size > 3) {
                    $("#spanfile").text("You can upload file up to 3 MB");
                    return false;
                }
                else {
                    $("#spanfile").text("");
                }
            }
        }

        $(function () {
            $("#fileToUpload").change(function () {
                checkfile();
            });
        });
    </script>
}
<br />
<br />
@Html.ActionLink("Back To Items", "Index")
<br />
<br />

MakerShop/MakerShop/Views/MyProducts/Create.cshtml
@model MakerShop.Models.Model

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Model</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ModelName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>*@




        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Download, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Download)
                    @Html.ValidationMessageFor(model => model.Download, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


       




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MakerShop/MakerShop/Views/MyProducts/Delete.cshtml
@model MakerShop.Models.Model

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Model</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Download)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Download)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MakerShop/MakerShop/Views/MyProducts/Details.cshtml
@model MakerShop.Models.Model

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Model</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Download)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Download)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ModelID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MakerShop/MakerShop/Views/MyProducts/Edit.cshtml
@model MakerShop.Models.Model

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Model</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ModelID)

        <div class="form-group">
            @Html.LabelFor(model => model.ModelName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ModelName, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModelName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>*@



        <div class="form-group">
            @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Download, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Download)
                    @Html.ValidationMessageFor(model => model.Download, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MakerShop/MakerShop/Views/MyProducts/Index.cshtml
@model IEnumerable<MakerShop.Models.Model>

@{
    ViewBag.Title = "Index";
}
<script src="scripts/simpleCart.js" type="text/javascript" charset="utf-8"></script>

<!--Make a new cart instance with your paypal login email-->
<script type="text/javascript">
    simpleCart = new cart("brett@wojodesign.com");
</script>



<h2>Index</h2>





<p>
    @Html.ActionLink("Create New", "Create")
  
</p>

<p>
    @Html.ActionLink("Home", "Index", "Home")

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ModelName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Size)
        </th>*@
        @*<th>
            @Html.DisplayNameFor(model => model.Download)
        </th>*@
        <th>

           Designer
            @*@Html.DisplayNameFor(model => model.User.UserName)*@
        </th>
        <th></th>
    </tr>
    @*<ul id="catalog">*@
        @foreach (var item in Model)
        {


            <tr>
                <td>
             
                    @*<img src="~/Content/robot.jpg" alt="" />*@

                 @{string productsPic = item.ModelName + ".jpg";}

                

                <img src="~/Content/@productsPic" alt="" />

                    <br />
                    

                <span class="price">@Html.DisplayFor(modelItem => item.ModelName)</span>

            


            </td>

               
                
           

            <td>
                @Html.DisplayFor(modelItem => item.User.UserName) 


            </td>
               
            <td>
        
           

                <a href="#" onclick="simpleCart.add('name= @Html.DisplayFor(modelItem => item.ModelName)', 'price=@item.Size', 'image=Content/@productsPic'); return false;"> add to cart</a>

            </td>
                <td></td><td></td><td></td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ModelID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ModelID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ModelID }) |
                @Html.ActionLink("Add an Image", "AddImage") |
                
            </td>
            </tr>
        }

</table>